name: Publish

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      android_beta:
        description: 'Android Beta'
        required: false
        default: false
        type: boolean
      ios_beta:
        description: 'iOS Beta'
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{  github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  flutter_channel: 'stable'
  flutter_version: '3.0.0'
  java_version: '12.x'
  ios_device: 'iPhone 11 Pro (14.5)'
  # Common environment variables used inside ./build_scripts files
  FASTLANE_SKIP_UPDATE_CHECK: '1'

jobs:
  publish_ios_beta:
    name: Publish iOS Beta
    if: (github.event_name == 'push' && contains(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.ios_beta == 'true')
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: |
            /Users/runner/hostedtoolcache/flutter
            ~/application/ios/Pods
          key: ios-flutter-${{ env.flutter_version }}
          restore-keys: |
            ios-flutter-cache-

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build and submit new internal iOS version to app center
        timeout-minutes: 25
        env:
          PROVISIONING_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          APPCENTER_IOS_BETA_TOKEN: ${{ secrets.APPCENTER_IOS_BETA_TOKEN }}
        run: |
          fastlane publish platform:ios build_type:release store:true

  publish_android_beta:
    name: Publish Android Beta
    if: (github.event_name == 'push' && contains(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.android_beta  == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Fix fastlane permissions
        run: sudo chmod -R a+w /var/lib/gems/

      - name: Build and submit new internal Android version to app center
        timeout-minutes: 20
        env:
          PROVISIONING_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          APPCENTER_ANDROID_BETA_TOKEN: ${{ secrets.APPCENTER_ANDROID_BETA_TOKEN }}
        run: |
          fastlane publish platform:android build_type:release store:true